version: '3'

services:
  app:
    build:
      context: .
      args:
        WORKDIR: $WORKDIR
    tty: true
    # command: yarn install && yarn dev
    ports:
      - "$FRONT_PORT:$CONTAINER_PORT"
      - "24678:24678"
    volumes:
      - ".:/nuxt3-app"
